NAME: 'C40_eff-20frames'
OUTPUT_DIR: './output/C40'
SHOW_STEP: 5000
SAVE_STEP: 1
VALID_STEP: 1
INPUT_SIZE: (380, 380)
RESUME_MODEL: ""
CPU_MODE: False
RANDOM_SEED: 8664

DATASET:
  DATASET_TRAIN: 'EFF_SET'
  DATASET_VALID: 'EFF_VALID'
  ROOT: '/mnt/lvdisk1/miaodata/FF/'
  TRAIN_TXT: 'train_c40.txt'
  VALID_TXT: 'valid_c40.txt'
  TRAIN_FRAMES: 20
  VALID_FRAMES: 5
  REALFAKE: 4

BACKBONE:
  TYPE: 'EfficientNetAutoB7'
  DROPOUT_RATE: 0

LOSS:
  LOSS1_TYPE: 'BCE_Loss'


TRAIN:
  BATCH_SIZE: 24
  MAX_EPOCH: 30
  NUM_WORKERS: 4
  TENSORBOARD:
    ENABLE: True
  OPTIMIZER:
    TYPE: 'ADAM'
    BASE_LR: 1e-5
  LR_SCHEDULER:
    TYPE: 'reduce'
    LR_FACTOR: 0.1
    PATIENCE: 10


TEST:
  BATCH_SIZE: 32
  NUM_WORKERS: 1